### ISSUE TITLE
Viewing All Upcoming Stages

### ISSUE THREAD

**Issue by Hatamitch** [misenhower/splatoon3.ink#10]
Will there be a feature to view all the upcoming stages in the future pipeline? This is available in Splatoon2.ink and it’s the feature I used the most previously. I hope this feature will be available down the line. 

Thank you for making this site, I love it and I use it daily!

**Comment by misenhower** [comment]
Yes! This is the next thing I'm going to be working on. Sorry this has taken so long, I've had a lot of other things going on lately 😄 

Glad to hear you like the site!

**Comment by misenhower** [comment]
Hey there, this is now available on the site!

![image](https://user-images.githubusercontent.com/1619746/198856256-32ff0240-f33f-4917-8987-fb01a89a77b4.png)
![image](https://user-images.githubusercontent.com/1619746/198856261-3214c4f2-2646-46aa-a827-af3f5becc115.png)

**Comment by Hatamitch** [comment]
Yessss! Thank you for making this!
