### ISSUE TITLE
Official Splatoon3.ink Discord Bot

### ISSUE THREAD

**Issue by Voroniyx** [misenhower/splatoon3.ink#12]
I think https://splatoon3.ink is really great, kudos to them.
I got an idea while scrolling through the code of https://splatoon3.ink: if there is a Twitter bot, why isn't there a Discord bot?

I am a Discord Bot Dev myself (I prefer to work with discord.js and mongoose).

I was thinking about features like updating embeds for Salmon Run, Rank/Turf War and Gear and also such slash commands.

I'd be interested to know if you could customise something like that?

I would be interested in making such a bot.

~ Discord: Am I Voroniyx?#2560 (863453422632173568)

**Comment by misenhower** [comment]
Hey @Voroniyx, glad to hear you like the site!

Unfortunately I don't have enough time to maintain a Discord bot along with everything else, but there are a number of other people who have made Discord bots that use data from Splatoon3.ink. The first one that comes to mind is [Spyke](https://discordbots.org/bot/340354052715970563), but I know there are several others as well.

If you're interested in making your own, I would encourage you to check out the [Data Access](https://github.com/misenhower/splatoon3.ink/wiki/Data-Access) page, which lists out all the various data URLs available from Splatoon3.ink. That should help you get started.

Anyway, thanks for writing and best of luck with your bot!
