### ISSUE TITLE
[Bug] <ScheduleRow> display `vsRule.name` without i18n

### ISSUE THREAD

**Issue by TenviLi** [misenhower/splatoon3.ink#14]
You will see this bug on the small screen.

![01C147B2-E67B-4FFB-8226-DB59C128B7D3](https://user-images.githubusercontent.com/30214981/198957961-7715e48a-77c3-4c45-a8d6-c398243d6294.png)

**Comment by misenhower** [comment]
Thanks for the bug report & fix! 😃
