### ISSUE TITLE
[Bug]  <GearCard> `font-family` missing `font-splatoon2`, display characters as '⎕'

### ISSUE THREAD

**Issue by TenviLi** [misenhower/splatoon3.ink#19]
You can see this bug at <https://splatoon3.ink/gear>

![image](https://user-images.githubusercontent.com/30214981/199479671-ac1d9aca-5271-4119-8b77-4cd808057a1a.png)
![image](https://user-images.githubusercontent.com/30214981/199479807-6c284bf1-233d-4053-8573-f96e913211a4.png)

**Comment by TenviLi** [comment]
> Hey @TenviLi, I think the issue here is that your Chromium build is missing some fonts. I just tested generating screenshots for `zh-CN` and this text seems to show up correctly for me:
> 
> ![gear dailydrop](https://user-images.githubusercontent.com/1619746/199526216-809e4f78-9502-4dd7-9477-1448e9a5924b.png)
> 
> ![gear regular](https://user-images.githubusercontent.com/1619746/199526232-d759f699-94ea-41f6-81da-f09bee8dcf5a.png)
> 
> Take a look at [this line](https://github.com/misenhower/splatoon3.ink/blob/7689ef7bdc9b82f1e6269c73052035d5ca8de288/docker/app/Dockerfile#L10) in my Dockerfile config. There might be some packages there you're missing.

Yes. This is the normal situation, missing fonts will be found from the font list that comes with the system

But the font-family is still wrong, does it is Segeo UI(?), not the splatoon fonts.

**Comment by phoebethewitch** [comment]
> But the font-family is still wrong, does it is WenQuanYi Zen Hei(?), not the splatoon fonts.

I think it being a more normal font makes a bit more sense here because of the small text. The Splatoon fonts are kinda hard to read at a small size. 

This is also consistent with how SplatNet 3 displays the time remaining in the app. 
![](https://uploads.catgirlin.space/2022/11_02/633a5dd49913b70ceaaaba8a8ef993c2c5509c03.png)

**Comment by TenviLi** [comment]
> I think it being a more normal font makes a bit more sense here because of the small text. The Splatoon fonts are kinda hard to read at a small size.

Well, I agree with you, readability also needs to be considered.
