### ISSUE TITLE
Faulty Gear response?

### ISSUE THREAD

**Issue by Glazelf** [misenhower/splatoon3.ink#2]
Is this as intended? The data retrieved from https://splatoon3.ink/data/gear.json seems to just be HTML? lol
![image](https://user-images.githubusercontent.com/35176230/190882269-353492f3-9d5c-4b7e-8d8d-846a214cbd75.png)

**Comment by misenhower** [comment]
You have an extra ; at the end of the URL :)

**Comment by Glazelf** [comment]
> You have an extra ; at the end of the URL :)

Lol thanks, I didn't think about checking the URL since I got a proper response at all. That's stupid, I'd have expected it to just not return 200. 
It was 4am when I did this haha, closing this.

**Comment by misenhower** [comment]
Yeah, you're right, it should return a 404. The reason that's happening is because of JS SPA config stuff, but I might be able to improve it. Thanks and good luck!
