### ISSUE TITLE
Is there a weapon API here?

### ISSUE THREAD

**Issue by landuo** [misenhower/splatoon3.ink#3]
I want a API with splatoon3's all weapon, can you please help me ?

**Comment by kerfuzzle** [comment]
splatoon3.ink provides data on the current stage rotations from SplatNet 3 (part of the Nintendo Switch online app). If you're looking for weapon stats and data then https://leanny.github.io/splat3/database.html ([Source](https://github.com/Leanny/leanny.github.io)) has lots of data for Splatoon 3

**Comment by landuo** [comment]
thank you.
