### ISSUE TITLE
Big Run Schedules don't show

### ISSUE THREAD

**Issue by TiagoGamer26** [misenhower/splatoon3.ink#40]
I don't know if this is intended but the Big Run schedule that starts tomorrow doesn't show up in the schedules.json file and is completely skipped.

**Comment by FieryFlames** [comment]
it's under `bigRunSchedules`, not `regularSchedules`

**Comment by misenhower** [comment]
FYI there's also a new `teamContestSchedules` which I believe will be used for Eggstra Credit in the future.

Don't ask me why Nintendo chose to organize the data this way 😄

**Comment by TiagoGamer26** [comment]
Thank you!

**Comment by Inkception** [comment]
No, it's under `https://splatoon3.ink/data/schedules.json`
