### ISSUE TITLE
No image url in X-Rank Data

### ISSUE THREAD

**Issue by kayanouriko** [misenhower/splatoon3.ink#44]
All image value retrun empty object in `xrank.takoroka.json` `xrank.tentatek.json.`
![1](https://user-images.githubusercontent.com/16263287/235102719-b5274c0f-6470-49d9-a06c-78ba74ae7da1.png)

By the way, can the `byname` support internationalization?

**Comment by misenhower** [comment]
Hey @kayanouriko, sorry about that! This should be fixed now.

I'm looking into your `byname` question too. I don't want to increase the size of the localization files too much, so I might end up doing this a slightly different way. I'll look at that a little later.

Thanks for reporting this issue!

**Comment by misenhower** [comment]
Ok, I looked into adding translations for `byname`: unfortunately, that would require a lot more http requests and make updating all the leaderboard data quite a lot slower.

I'd recommend using pre-existing lists of the adjectives/subjects to translate them instead. @aeonsake has a list of them here:
* [Adjectives](https://gitlab.com/AeonSake/splat3-data/-/blob/master/MSBT/JSON_merged/CommonMsg/Byname/BynameAdjective.msbt.json)
* [Subjects](https://gitlab.com/AeonSake/splat3-data/-/blob/master/MSBT/JSON_merged/CommonMsg/Byname/BynameSubject.msbt.json)

**Comment by kayanouriko** [comment]
Thanks for the fix. ٩(ˊᗜˋ*)و
