### ISSUE TITLE
Challenges schedule

### ISSUE THREAD

**Issue by jackssrt** [misenhower/splatoon3.ink#45]
Are there any plans to add the new Sizzle Season Challenges schedule?

**Comment by Inkception** [comment]
yup, they have been added yesterday evening!

**Comment by misenhower** [comment]
@jackssrt The data is available now in `schedules.json`, and @Inkception is hard at work adding UI to the site. Stay tuned!

**Comment by kerfuzzle** [comment]
Challenges page looks really nice, GJ!
