### ISSUE TITLE
Mobile appify website like splatoon2.ink

### ISSUE THREAD

**Issue by sburbol** [misenhower/splatoon3.ink#6]
Adding the splatoon3.ink site to home screen in Android (not sure about iOS) makes a link to the site as expected but does not show the favicon or load as its own single page. splatoon2.ink does this already.
Not actually sure what the term for this is, and it is just cosmetic but looks and feels nicer.

Thanks for your work on this site, it's awesome and I use it daily :)

**Comment by Rexogamer** [comment]
You're thinking of a [PWA](https://en.wikipedia.org/wiki/Progressive_Web_App) ^^

**Comment by sburbol** [comment]
That's the term I was looking for, thanks!

**Comment by misenhower** [comment]
This should be better now, let me know how it goes!
