### ISSUE TITLE
schedules.json is not updated.

### ISSUE THREAD

**Issue by shngmsw** [misenhower/splatoon3.ink#8]
I always use the data on DiscordBot. Thanks.

It looks like https://splatoon3.ink/data/schedules.json is not updated.
It stops at "startTime": "2022-10-07T14:00:00Z".

**Comment by misenhower** [comment]
Hey there, this should be fixed now. There were some changes to the Nintendo API that caused my updater to stop working.

Thanks for letting me know!

**Comment by shngmsw** [comment]
Thanks!
Appreciate the quick response!
